# @package _group_
parameters:
  learning_rate: 0.01
  max_depth: 1
  min_sum_hessian_in_leaf: 1.0
  gamma: 0.0
  feature_fraction: 0.8
  bagging_fraction: 0.8
  lambda_l1: 0.0
  lambda_l2: 1.0
  objective: "multiclass"
  metric: "multi_logloss"
  num_class: 3

file: 'lgbm_class'
name: 'lgbm'
