model:
  learning_rate: 0.05
  max_depth: 5
  min_sum_hessian_in_leaf: 1.0
  gamma: 0.0
  feature_fraction: 0.8
  bagging_fraction: 0.8
  lambda_l1: 0.0
  lambda_l2: 1.0
  objective: "regression"
  metric: "mse"
