defaults:
  - model: lgbm_class

features: ["sepal_length",
           "sepal_width",
           "petal_length",
           "petal_width"]
target_name: "target"
ID_name: "index"
cloud: true

bucket_name: "ml-project-iris"
project_id: "ml-platform-303306"
